<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-7SMJUAE" name="Test" tests="9" failures="3" timestamp="15 May 2019 16:42:41 GMT" time="0.069" errors="0">
  <testcase name="TestOne" time="0.021" classname="testNgDemo.DemoTest1"/>
  <testcase name="TestTwo" time="0.001" classname="testNgDemo.DemoTest1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testNgDemo.DemoTest1.TestTwo(DemoTest1.java:16)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- TestTwo -->
  <testcase name="TestThird" time="0.0" classname="testNgDemo.DemoTest1">
    <skipped/>
  </testcase> <!-- TestThird -->
  <testcase name="TestTwo" time="0.0" classname="testNgDemo.DemoTest2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testNgDemo.DemoTest2.TestTwo(DemoTest2.java:16)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- TestTwo -->
  <testcase name="TestOne" time="0.0" classname="testNgDemo.DemoTest2"/>
  <testcase name="TestThird" time="0.0" classname="testNgDemo.DemoTest2">
    <skipped/>
  </testcase> <!-- TestThird -->
  <testcase name="TestOne" time="0.0" classname="testNgDemo.DemoTest3"/>
  <testcase name="TestTwo" time="0.0" classname="testNgDemo.DemoTest3">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testNgDemo.DemoTest3.TestTwo(DemoTest3.java:16)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- TestTwo -->
  <testcase name="TestThird" time="0.001" classname="testNgDemo.DemoTest3">
    <skipped/>
  </testcase> <!-- TestThird -->
</testsuite> <!-- Test -->
